export const fish = [
  {
    id: "1",
    name: "Giant Snakehead",
    location: "Pond",
    value: "5500",
    months: "[June, July, August]",
    time: "9 a.m. - 4 p.m.",
    shadow: "X Large",
  },
  {
    id: "2",
    name: "Betta",
    location: "River",
    value: "2500",
    months: "[May, June, July, August, September, October]",
    time: "5 p.m. - 9 a.m.",
    shadow: "Small",
  },
  {
    id: "3",
    name: "Angelfish",
    location: "River",
    value: "3000",
    months: "[May, June, July, August, September, October]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Small",
  },
  {
    id: "4",
    name: "Bitterling",
    location: "River",
    value: "900",
    months: "[January, February, March, November, December]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "5",
    name: "Blowfish",
    location: "Sea",
    value: "5000",
    months: "[January, February, November, December]",
    time: "6 p.m. - 4 a.m.",
    shadow: "Medium",
  },
  {
    id: "6",
    name: "Piranha",
    location: "River",
    value: "2500",
    months: "[June, July, August, September]",
    time: "9 a.m. - 4 p.m., 9 p.m. - 4 a.m.",
    shadow: "Small",
  },
  {
    id: "7",
    name: "Horse Mackerel",
    location: "Sea",
    value: "150",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "8",
    name: "King Salmon",
    location: "River (mouth)",
    value: "1800",
    months: "[September]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "9",
    name: "Rainbowfish",
    location: "River",
    value: "800",
    months: "[May, June, July, August, September, October]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Small",
  },
  {
    id: "10",
    name: "Bluegill",
    location: "River",
    value: "180",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Small",
  },
  {
    id: "11",
    name: "Barred Knifejaw",
    location: "Sea",
    value: "5000",
    months:
      "[March, April, May, June, July, August, September, October, November]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "12",
    name: "Zebra Turkeyfish",
    location: "Sea",
    value: "500",
    months: "[April, May, June, July, August, September, October, November]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "13",
    name: "Red Snapper",
    location: "Sea",
    value: "3000",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "14",
    name: "Tadpole",
    location: "Pond",
    value: "100",
    months: "[March, April, May, June,July]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "15",
    name: "Barreleye",
    location: "Sea",
    value: "15000",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "9 p.m. - 4 a.m.",
    shadow: "Small",
  },
  {
    id: "16",
    name: "Catfish",
    location: "Pond",
    value: "800",
    months: "[May, June, July, August, September, October]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "17",
    name: "Char",
    location: "River/Pond",
    value: "3800",
    months: "[March, April, May, June,September, October, November]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Medium",
  },
  {
    id: "18",
    name: "Football Fish",
    location: "Sea",
    value: "2500",
    months: "[January, February, March, November, December]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "19",
    name: "Ribbon Eel",
    location: "Sea",
    value: "600",
    months: "[June, July, August, September, October]",
    time: "All day",
    shadow: "Narrow",
  },
  {
    id: "20",
    name: "Arapaima",
    location: "River",
    value: "10000",
    months: "[June, July, August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest",
  },
  {
    id: "21",
    name: "Butterfly Fish",
    location: "Sea",
    value: "1000",
    months: "[April, May, June, July, August, September]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "22",
    name: "Carp",
    location: "Pond",
    value: "300",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Large",
  },
  {
    id: "23",
    name: "Gar",
    location: "Pond",
    value: "6000",
    months: "[July, August, September, October]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest",
  },
  {
    id: "24",
    name: "Mitten Crab",
    location: "River",
    value: "2000",
    months: "[ September, October, November]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Small",
  },
  {
    id: "25",
    name: "Coelacanth",
    location: "Sea (rainy days)",
    value: "15000",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Largest",
  },
  {
    id: "26",
    name: "Giant Trevally",
    location: "Pier",
    value: "4500",
    months: "[May, June, July, August, September, October]",
    time: "All day",
    shadow: "Large",
  },
  {
    id: "27",
    name: "Goldfish",
    location: "Pond",
    value: "1300",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "28",
    name: "Pike",
    location: "River",
    value: "1800",
    months: "[September, October, November, December]",
    time: "All day",
    shadow: "X Large",
  },
  {
    id: "29",
    name: "Tuna",
    location: "Pier",
    value: "7000",
    months: "[January, February, March, April, November, December]",
    time: "All day",
    shadow: "X Large",
  },
  {
    id: "30",
    name: "Yellow Perch",
    location: "River",
    value: "300",
    months: "[January, February, March, October, November, December]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "31",
    name: "Dorado",
    location: "River",
    value: "15000",
    months: "[June, July, August, September]",
    time: "4 a.m - 9 p.m.",
    shadow: "X Large",
  },
  {
    id: "32",
    name: "Mahi-mahi",
    location: "Sea",
    value: "6000",
    months: "[May, June, July, August, September, October]",
    time: "All day",
    shadow: "Large",
  },
  {
    id: "33",
    name: "Moray Eel",
    location: "Sea",
    value: "2000",
    months: "[August, September, October, November]",
    time: "All day",
    shadow: "X Large",
  },
  {
    id: "34",
    name: "Killifish",
    location: "Pond",
    value: "300",
    months: "[April, May, June, July, August]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "35",
    name: "Koi",
    location: "Pond",
    value: "4000",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "36",
    name: "Ocean Sunfish",
    location: "Sea",
    value: "4000",
    months: "[July, August, September]",
    time: "4 a.m. - 9 p.m.",
    shadow: "(Fin)",
  },
  {
    id: "37",
    name: "Neon Tetra",
    location: "River",
    value: "500",
    months: "[April, May, June, July, August, September, October, November]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Smallest",
  },
  {
    id: "38",
    name: "Clown Fish",
    location: "Sea",
    value: "650",
    months: "[April, May, June, July, August, September]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "39",
    name: "Frog",
    location: "Pond",
    value: "200",
    months: "[May, June, July, August]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "40",
    name: "Oarfish",
    location: "Sea",
    value: "9000",
    months: "[January, February, March, April, May, December]",
    time: "All day",
    shadow: "Largest",
  },
  {
    id: "41",
    name: "Snapping Turtle",
    location: "River",
    value: "5000",
    months: "[April, May, June, July, August, September, October]",
    time: "9 p.m. - 4 a.m.",
    shadow: "X Large",
  },
  {
    id: "42",
    name: "Tilapia",
    location: "River",
    value: "800",
    months: "[June, July, August, September, October]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "43",
    name: "Saddled Bichir",
    location: "River",
    value: "4000",
    months: "[June, July, August, September]",
    time: "9 p.m. - 4 a.m.",
    shadow: "Large",
  },
  {
    id: "44",
    name: "Sea Horse",
    location: "Sea",
    value: "1100",
    months: "[April, May, June, July, August, September, October, November]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "45",
    name: "Pop-eyed Goldfish",
    location: "Pond",
    value: "1300",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Smallest",
  },
  {
    id: "46",
    name: "Stringfish",
    location: "River (Clifftop)",
    value: "15000",
    months: "[January, February, March, December]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest",
  },
  {
    id: "47",
    name: "Great White Shark",
    location: "Sea",
    value: "15000",
    months: "[June, July, August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest (fin)",
  },
  {
    id: "48",
    name: "Hammerhead Shark",
    location: "Sea",
    value: "8000",
    months: "[June, July, August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest (fin)",
  },
  {
    id: "49",
    name: "Dace",
    location: "River",
    value: "240",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Medium",
  },
  {
    id: "50",
    name: "Guppy",
    location: "River",
    value: "1300",
    months: "[April, May, June, July, August, September, October, November]",
    time: "betta",
    shadow: "Smallest",
  },
  {
    id: "51",
    name: "Golden Trout",
    location: "River (Clifftop)",
    value: "15000",
    months: "[March, April, May, June,September, October, November]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "52",
    name: "Squid",
    location: "Sea",
    value: "500",
    months:
      "[January, February, March, April, May, June, July, August, December]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "53",
    name: "Crucian Carp",
    location: "River",
    value: "160",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "54",
    name: "Ray",
    location: "Sea",
    value: "3000",
    months: "[April, May, June, July, August, September]",
    time: "4 a.m. - 9 p.m.",
    shadow: "X Large",
  },
  {
    id: "55",
    name: "Black Bass",
    location: "River",
    value: "400",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Large",
  },
  {
    id: "56",
    name: "Arowana",
    location: "River",
    value: "10000",
    months: "[June, July, August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "57",
    name: "Anchovy",
    location: "Sea",
    value: "200",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "4 a.m. - 9 p.m.",
    shadow: "Small",
  },
  {
    id: "58",
    name: "Ranchu Goldfish",
    location: "Pond",
    value: "4500",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Small",
  },
  {
    id: "59",
    name: "Cherry Salmon",
    location: "River",
    value: "1000",
    months: "[March, April, May, June,September, October, November]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "60",
    name: "Pale Chub",
    location: "River",
    value: "200",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Smallest",
  },
  {
    id: "61",
    name: "Blue Marlin",
    location: "Pier",
    value: "10000",
    months:
      "[January, February, March, April, July, August, September, November, December]",
    time: "All day",
    shadow: "X Large",
  },
  {
    id: "62",
    name: "Freshwater Goby",
    location: "River",
    value: "400",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Small",
  },
  {
    id: "63",
    name: "Crawfish",
    location: "Pond",
    value: "200",
    months: "[April, May, June, July, August, September]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "64",
    name: "Napoleonfish",
    location: "Sea",
    value: "10000",
    months: "[July, August]",
    time: "4 a.m. - 9 p.m.",
    shadow: "Largest",
  },
  {
    id: "65",
    name: "Dab",
    location: "Sea",
    value: "300",
    months: "[January, February, March, April, October, November, December]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "66",
    name: "Saw Shark",
    location: "Sea",
    value: "12000",
    months: "[June, July, August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Largest (fin)",
  },
  {
    id: "67",
    name: "Soft-shelled Turtle",
    location: "River",
    value: "3750",
    months: "[August, September]",
    time: "4 p.m. - 9 a.m.",
    shadow: "Large",
  },
  {
    id: "69",
    name: "Salmon",
    location: "River (mouth)",
    value: "700",
    months: "[September]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "70",
    name: "Pond Smelt",
    location: "River",
    value: "500",
    months: "[January, February, December]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "71",
    name: "Olive Flounder",
    location: "Sea",
    value: "800",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Large",
  },
  {
    id: "72",
    name: "Sturgeon",
    location: "River (mouth)",
    value: "10000",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "Largest",
  },
  {
    id: "73",
    name: "Sea Bass",
    location: "Sea",
    value: "400",
    months:
      "[January, February, March, April, May, June, July, August, September, October, November, December]",
    time: "All day",
    shadow: "X Large",
  },
  {
    id: "74",
    name: "Whale Shark",
    location: "Sea",
    value: "13000",
    months: "[June, July, August, September]",
    time: "All day",
    shadow: "Largest (fin)",
  },
  {
    id: "75",
    name: "Suckerfish",
    location: "Sea",
    value: "1500",
    months: "[June, July, August, September]",
    time: "All day",
    shadow: "(Fin)",
  },
  {
    id: "76",
    name: "Loach",
    location: "River",
    value: "400",
    months: "[March, April, May]",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "77",
    name: "Nibble Fish",
    location: "River",
    value: "1500",
    months: "[May, June, July, August, September]",
    time: "9 a.m. - 4 p.m.",
    shadow: "Small",
  },
  {
    id: "78",
    name: "Sea Butterfly",
    location: "Sea",
    value: "1000",
    months: "[January, February, March, December]",
    time: "All day",
    shadow: "Smallest",
  },
  {
    id: "79",
    name: "Surgeonfish",
    location: "Sea",
    value: "1000",
    months: " [April, May, June, July, August, September] ",
    time: "All day",
    shadow: "Small",
  },
  {
    id: "80",
    name: "Sweetfish",
    location: "River",
    value: "900",
    months: "[July, August, September]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "81",
    name: "Puffer Fish",
    location: "Sea",
    value: "250",
    months: "[July, August, September]",
    time: "All day",
    shadow: "Medium",
  },
  {
    id: "82",
    name: "Common butterfly",
    location: "Above Flowers",
    value: "160",
    time: "4AM - 7PM",
  },
  {
    id: "83",
    name: "Yellow butterfly",
    location: "Flying",
    value: "160",
    time: "4AM - 7PM",
  },
  {
    id: "84",
    name: "Tiger Butterfly",
    location: "Above Flowers",
    value: "240",
    time: "4AM - 7PM",
  },
  {
    id: "85",
    name: "Peacock Butterfly",
    location: "Flying (Hybrid Flowers)",
    value: "2,500",
    time: "4AM - 7PM",
  },
  {
    id: "86",
    name: "Common bluebottle",
    location: "Above Flowers",
    value: "300",
    time: "4AM - 7PM",
  },
  {
    id: "87",
    name: "Paper Kite Butterfly",
    location: "Flying",
    value: "1000",
    time: "8AM - 7PM",
  },
  {
    id: "88",
    name: "Great Purple Emperor",
    location: "Above Flowers",
    value: "3000",
    time: "4AM - 7PM",
  },
  {
    id: "89",
    name: "Monarch butterfly",
    location: "Flying",
    value: "140",
    time: "4AM - 5PM",
  },
  {
    id: "90",
    name: "Emperor Butterfly",
    location: "Flying",
    value: "4,000",
    time: "5PM - 8AM",
  },
  {
    id: "91",
    name: "Agrias Butterfly",
    location: "Flying",
    value: "3000",
    time: "8AM - 5PM",
  },
  {
    id: "92",
    name: "Rajah brooke's birdwing",
    location: "flying",
    value: "2500",
    time: "8AM - 5PM",
  },
  {
    id: "93",
    name: "Queen Alexandra's Birdwing",
    location: "Flying",
    value: "4000",
    time: "8AM - 4PM",
  },
  {
    id: "94",
    name: "Moth",
    location: "Near Lights",
    value: "130",
    time: "7PM - 4AM",
  },
  {
    id: "95",
    name: "Atlas moth",
    location: "On Trees",
    value: "3000",
    time: "7PM - 4AM",
  },
  {
    id: "96",
    name: "Madagascan sunset moth",
    location: "Flying",
    value: "2500",
    time: "8AM - 4PM",
  },
  {
    id: "97",
    name: "Long locust",
    location: "In Grass",
    value: "200",
    time: "8AM - 4PM",
  },
  {
    id: "98",
    name: "Migratory Locust",
    location: "In Grass",
    value: "200",
    time: "8AM - 7PM",
  },
  {
    id: "99",
    name: "Rice grasshopper",
    location: "In Grass",
    value: "1600",
    time: "8AM - 7PM",
  },
  {
    id: "100",
    name: "Grasshopper",
    location: "In Grass",
    value: "160",
    time: "8AM - 5PM",
  },
  {
    id: "101",
    name: "Cricket",
    location: "In Grass",
    value: "130",
    time: "5PM - 8AM",
  },
  {
    id: "102",
    name: "Bell cricket",
    location: "In Grass",
    value: "430",
    time: "5PM - 8AM",
  },
  {
    id: "103",
    name: "Mantis",
    location: "On Flowers",
    value: "430",
    time: "8AM - 5PM",
  },
  {
    id: "104",
    name: "Orchid mantis",
    location: "On Flowers",
    value: "2400",
    time: "8AM - 5PM",
  },
  {
    id: "105",
    name: "Honeybee",
    location: "Above Flowers",
    value: "200",
    time: "8AM - 5PM",
  },
  {
    id: "106",
    name: "Wasp",
    location: "Shaking Trees",
    value: "2500",
    time: "All day",
  },
  {
    id: "107",
    name: "Brown Cicada",
    location: "On Trees",
    value: "250",
    time: "8AM - 5PM",
  },
  {
    id: "108",
    name: "Robust Cicada",
    location: "On Trees",
    value: "300",
    time: "8AM - 5PM",
  },
  {
    id: "109",
    name: "Giant Cicada",
    location: "On Trees",
    value: "500",
    time: "8AM - 5PM",
  },
  {
    id: "110",
    name: "Walker cicada",
    location: "On Trees",
    value: "400",
    time: "8AM - 4PM",
  },
  {
    id: "111",
    name: "Evening Cicada",
    location: "On Trees",
    value: "550",
    time: "4AM - 8AM,\r\n4PM - 7PM",
  },
  {
    id: "112",
    name: "Cicada Shell",
    location: "On Trees",
    value: "10",
    time: "All day",
  },
  {
    id: "113",
    name: "Red dragonfly",
    location: "Flying",
    value: "180",
    time: "8AM - 7PM",
  },
  {
    id: "114",
    name: "Darner dragonfly",
    location: "Flying",
    value: "230",
    time: "8AM - 5PM",
  },
  {
    id: "115",
    name: "Banded dragonfly",
    location: "Flying",
    value: "4500",
    time: "8AM - 5PM",
  },
  {
    id: "116",
    name: "Damselfly",
    location: "Flying",
    value: "500",
    time: "All day",
  },
  {
    id: "117",
    name: "Firefly",
    location: "Above Freshwater",
    value: "300",
    time: "7PM - 4PM",
  },
  {
    id: "118",
    name: "Mole Cricket",
    location: "Underground",
    value: "500",
    time: "All day",
  },
  {
    id: "119",
    name: "Pondskater",
    location: "Water's Surface",
    value: "130",
    time: "8AM - 7PM",
  },
  {
    id: "120",
    name: "Diving beetle",
    location: "Water's Surface",
    value: "800",
    time: "8AM - 7PM",
  },
  {
    id: "121",
    name: "Giant water bug",
    location: "Water's Surface",
    value: "2000",
    time: "7PM - 8PM",
  },
  {
    id: "122",
    name: "Stinkbug",
    location: "On Flowers",
    value: "120",
    time: "All day",
  },
  {
    id: "123",
    name: "Man-Faced Stink Bug",
    location: "On Flowers",
    value: "1000",
    time: "7PM - 8AM",
  },
  {
    id: "124",
    name: "Ladybug",
    location: "On Flowers",
    value: "200",
    time: "8AM - 5PM",
  },
  {
    id: "125",
    name: "Tiger beetle",
    location: "Flying",
    value: "1500",
    time: "All day",
  },
  {
    id: "126",
    name: "Jewel Beetle",
    location: "On Trees, Tree Stumps",
    value: "2400",
    time: "All day",
  },
  {
    id: "127",
    name: "Citrus Long-horned Beetle",
    location: "On Tree Stumps",
    value: "350",
    time: "All day",
  },
  {
    id: "128",
    name: "Rosalia Batesi Beetle",
    location: "On Tree Stumps",
    value: "3000",
    time: "All day",
  },
  {
    id: "129",
    name: "Blue Weevil Beetle",
    location: "On Trees",
    value: "800",
    time: "All day",
  },
  {
    id: "130",
    name: "Violin beetle",
    location: "On Trees",
    value: "450",
    time: "All day",
  },
  {
    id: "131",
    name: "Dung beetle",
    location: "On Ground",
    value: "3000",
    time: "All day",
  },
  {
    id: "132",
    name: "Earth-boring dung beetle",
    location: "On Ground",
    value: "300",
    time: "All day",
  },
  {
    id: "133",
    name: "Scarab Beetle",
    location: "On Trees",
    value: "10000",
    time: "11PM - 8AM",
  },
  {
    id: "134",
    name: "Drone Beetle",
    location: "On Trees",
    value: "200",
    time: "All day",
  },
  {
    id: "135",
    name: "Goliath Beetle",
    location: "On Trees",
    value: "8000",
    time: "5PM - 8AM",
  },
  {
    id: "136",
    name: "Saw Stag",
    location: "On Trees",
    value: "2000",
    time: "All day",
  },
  {
    id: "137",
    name: "Miyama Stag",
    location: "On Trees",
    value: "1000",
    time: "All day",
  },
  {
    id: "138",
    name: "Giant Stag",
    location: "On Trees",
    value: "10000",
    time: "11PM - 8AM",
  },
  {
    id: "139",
    name: "Rainbow stag",
    location: "On Trees",
    value: "6000",
    time: "7PM - 8AM",
  },
  {
    id: "140",
    name: "Cyclommatus Stag",
    location: "On Trees",
    value: "8000",
    time: "5PM - 8AM",
  },
  {
    id: "141",
    name: "Golden Stag",
    location: "On Trees",
    value: "12000",
    time: "5PM - 8AM",
  },
  {
    id: "142",
    name: "Giraffe Stag",
    location: "On Trees",
    value: "12000",
    time: "5PM - 8AM",
  },
  {
    id: "143",
    name: "Horned Dynastid",
    location: "On Trees",
    value: "1350",
    time: "5PM - 8AM",
  },
  {
    id: "144",
    name: "Horned Atlas",
    location: "On Trees",
    value: "8000",
    time: "5PM - 8AM",
  },
  {
    id: "145",
    name: "Horned Elephant",
    location: "On Trees",
    value: "8000",
    time: "5PM - 8AM",
  },
  {
    id: "146",
    name: "Horned Hercules",
    location: "On Trees",
    value: "12000",
    time: "5PM - 8AM",
  },
  {
    id: "147",
    name: "Walking Stick",
    location: "On Trees",
    value: "600",
    time: "4AM - 8AM,\r\n5PM - 7PM",
  },
  {
    id: "148",
    name: "Walking Leaf",
    location: "On Ground (Beneath trees)",
    value: "600",
    time: "All day",
  },
  {
    id: "149",
    name: "Bagworm",
    location: "Falls from trees when shaking them",
    value: "600",
    time: "All day",
  },
  {
    id: "150",
    name: "Ant",
    location: "On rotten turnips and fruit",
    value: "80",
    time: "All day",
  },
  {
    id: "151",
    name: "Hermit crab",
    location: "On beach, disguised as a shell",
    value: "1000",
    time: "7PM - 8AM",
  },
  {
    id: "152",
    name: "Wharf roach",
    location: "On the rocky part of beaches",
    value: "200",
    time: "All Day",
  },
  {
    id: "153",
    name: "Fly",
    location: "On rotten food and garbage",
    value: "60",
    time: "All Day",
  },
  {
    id: "154",
    name: "Mosquito",
    location: "Flying",
    value: "130",
    time: "Night",
  },
  {
    id: "155",
    name: "Flea",
    location: "On Flea-Infested Villagers",
    value: "70",
    time: "All Day",
  },
  {
    id: "156",
    name: "Snail",
    location: "On rocks",
    value: "250",
    time: "All Day",
  },
  {
    id: "157",
    name: "Pill bug",
    location: "Spawns when hitting a rock",
    value: "250",
    time: "11PM - 4PM",
  },
  {
    id: "158",
    name: "Centipede",
    location: "Spawns when hitting a rock",
    value: "430",
    time: "5PM - 11PM",
  },
  {
    id: "159",
    name: "Spider",
    location: "Shaking Trees",
    value: "600",
    time: "7PM - 8AM",
  },
  {
    id: "160",
    name: "Tarantula",
    location: "On Ground",
    value: "8000",
    time: "7PM - 4AM",
  },
  {
    id: "161",
    name: "Scorpion",
    location: "On Ground",
    value: "8000",
    time: "7PM - 4AM",
  },
  {
    id: "162",
    name: "Manila Clam",
    location: "On beach",
    value: "100",
  },
  {
    id: "163",
    name: "Venus Comb",
    location: "On beach",
    value: "300",
  },
  {
    id: "164",
    name: "Cowrie",
    location: "On beach",
    value: "60",
  },
  {
    id: "165",
    name: "Coral",
    location: "On beach",
    value: "500",
  },
  {
    id: "166",
    name: "Sea Snail",
    location: "On beach",
    value: "180",
  },
  {
    id: "167",
    name: "Sand Dollar",
    location: "On beach",
    value: "120",
  },
  {
    id: "168",
    name: "Giant Clam",
    location: "On beach",
    value: "900",
  },
  {
    id: "169",
    name: "Conch",
    location: "On beach",
    value: "700",
  },
];
